apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-minecraft
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: helm-reconciler
  namespace: minecraft
subjects:
  - kind: ServiceAccount
    name: helm-minecraft
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: app-helm-reconciler
