apiVersion: v1
kind: Secret
metadata:
    name: pi-agent-secrets
    namespace: pi-agent
type: Opaque
stringData:
    AUTH_USERNAME: ENC[AES256_GCM,data:MZXCEz0ycMqz,iv:YrvhVAq5VsfD+yo/4gYG+pi85zEch20Ez96ASzSxuEQ=,tag:/Dyg4OQI/Kw0WiM9MHZIDA==,type:str]
    AUTH_PASSWORD: ENC[AES256_GCM,data:1XrCPJVTY+BnbtQcbuufzAo6REaL0Jpfx6Fgv0W5wd8=,iv:oP1HEasStFADNYoz/Jhdt54ikhGkDzB3yoiW+VZwQ5w=,tag:wD8heBumqAnPsyOLEz3lVw==,type:str]
    id_ed25519: ENC[AES256_GCM,data:xHKtnnjndcdObUKKdDvARZmjRgztoX1zYpz9N1n/DtglkYg/UgjWjynLW9hM3tZV0UwGw7G96ZkaiGIFuLO2BWv3u/mgP07Y42fQV3LjpnEOJdK9nTu1tBQbfRJsSFP0q2HhgUg5AoQrfG5k4sXJ8Pcdu26qMNlxLNlxcFIGBEKa4p92g+PvtOY7WFJSewECP9eJcLUzXfa/gOkl92malnXma+ul5CNUm5cvlBFmOBn2l6nlUvTspEcW6XOhZBFzGxRUMh+OARBYUa6/BLuqOepZPr6vIj8NarUs5v3v+X0IHTpwjsufnNDQMYMbgTy5dWDaqH+FOXzSnYcL4/qkrYFr5mXPlCR93VA/aTSZ06EBbfz3DxHRBfZKsSJEvbhYCuH2PKDx3YdEurKRBf3u7Nyv1TgAiLIEyuHMtDYyZPU6ps1xd/vX+IIU0uqMk3QhmImKI0SX3rI7sFDWsD7qC1B/EOn5+BUSUlYp2EFo1LJID7Pamyx+Tn0jh+y4eKLCwKg8uypXxb+XFdgzl50d,iv:3RULlqkFrXTyxwLZi/MInTEv4J6Sr2eIGtCx+znyfsg=,tag:RSBZFhgbCXerndZ6CUHu7w==,type:str]
    id_ed25519.pub: ENC[AES256_GCM,data:VA9hOPPPHk1Bxk7LLONH3b9+UM8/HN4d3ykPQqojkNfQlh2WLwooZwP5tww/3W+CFQYWW+zNUYICBo1Mg/wvze+owgWrY+1JNo7Q8iFuIJGDjkEEfPX8mJI=,iv:PP3R+S+HUQ+aLTQrhwUsv7Usyl2DFh553goQdlhrQGI=,tag:3poxUb6rZrezqAmuZt8PuQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxOVVBV2FkS1RDdjFROVkx
            YUMvTmtkWW9wVFRBN1hEY0RIWU1PRnY5YTFVCktRVVBEU0hwSjVkSUV5Yk41QVlJ
            QWRyblJ3RTdHaVhxTnFPc0h4WHFubWsKLS0tIDBVVmtRL0FpbkFFL0ZMZnFTVnNQ
            bUQ0TmJEZDk4NHBaUkcrYmxWNVFYUU0K5SVKlcqe1UyM/q3/q/jRtVcAurC8JP0z
            XFHnkI8tNlKImmwQOdsledx647ufuTh6qXhwlyLWs7/ITPTQvxtuIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-30T13:48:42Z"
    mac: ENC[AES256_GCM,data:IDj0kk9rz3OM17OoN2zpwfRgqhwELNgldUeDP/jfGNoov1a7wzbkq1U4dYrE53ujh+JUbAZAf1lZFE3a3xSY1S9gzWiDKO1lxg+uBl571X+AVIpxik2JxfgtQ0k9pCRiXIgz8FUVzA+fJpecw9gUsMZwspj045IAkgsCwBQnc3A=,iv:EB+JJUjp4iwl4r/3CmvPmQhDYgHKASH9RE6q9KnQSMw=,tag:OAAvacbOzmt6LzuwW1EgbQ==,type:str]
    version: 3.13.1
