apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - a50passos/flux.yaml
  - bestcarprice/flux.yaml
  - buffy/flux.yaml
  - home-assistant/flux.yaml
  - livinvicta/flux.yaml
  - minecraft/flux.yaml
  - payments/flux.yaml
  - payments-testing/flux.yaml
  - shell/flux.yaml
