apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-longhorn
  namespace: flux-system
spec:
  interval: 5m
  path: ./infrastructure/longhorn
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: longhorn-helmrelease
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-local-path
