apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-helmrelease
  namespace: flux-system
spec:
  interval: 5m
  releaseName: longhorn
  storageNamespace: longhorn-system
  targetNamespace: longhorn-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
  values:
    defaultSettings:
      autoCleanupWhenDeleteBackup: false
      replicaAutoBalance: best-effort
      replicaSoftAntiAffinity: true
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
    storageClass:
      reclaimPolicy: Delete