apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-helmrelease
  namespace: flux-system
spec:
  interval: 5m
  releaseName: longhorn
  storageNamespace: longhorn-system
  targetNamespace: longhorn-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  chart:
    spec:
      chart: longhorn
      sourceRef:
        kind: HelmRepository
        name: longhorn
  values:
    defaultSettings:
      autoCleanupWhenDeleteBackup: false
      replicaAutoBalance: best-effort
      replicaSoftAntiAffinity: true
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      reclaimPolicy: Delete
    storageClass:
      reclaimPolicy: Delete
    longhornManager:
      resources:
        requests:
          cpu: 100m
          memory: 192Mi
        limits:
          memory: 512Mi
    longhornUI:
      replicas: 1
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 512Mi
    longhornDriver:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 512Mi
    engineImage:
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          memory: 512Mi
    instanceManager:
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          memory: 768Mi
    csiAttacher:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 512Mi
    csiProvisioner:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi
    csiResizer:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi
    csiSnapshotter:
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 512Mi