apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 1m
  releaseName: longhorn
  targetNamespace: longhorn-system
  storageNamespace: longhorn-system
  serviceAccountName: helm-infrastructure
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 30m
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
  values:
    defaultBackupStore:
      backupTarget: s3://longhorn-backups@garage/
      backupTargetCredentialSecret: longhorn-backup-s3
      pollInterval: 300
    defaultSettings:
      autoCleanupWhenDeleteBackup: true
      concurrentReplicaRebuildPerNodeLimit: 1
      defaultDataLocality: best-effort
      defaultReplicaCount: 2
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      orphanResourceAutoDeletion: replica-data;instance
      replicaAutoBalance: best-effort
      replicaSoftAntiAffinity: false
      removeSnapshotsDuringFilesystemTrim: true
      snapshotMaxCount: 50
      storageOverProvisioningPercentage: 200
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 2
      reclaimPolicy: Delete
    storageClass:
      reclaimPolicy: Delete
    longhornUI:
      replicas: 1
