apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-controller-default
  namespace: flux-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: helm-infrastructure
  namespace: flux-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-infrastructure
subjects:
  - kind: ServiceAccount
    name: helm-infrastructure
    namespace: flux-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
