apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: default-proxy
spec:
  statefulSet:
    pod:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              tailscale.com/parent-resource: ts-proxies
      tailscaleContainer:
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
