apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - payments-testing-ci-rolebinding.yaml
  - mailpit.yaml
  - payments-testing-git.yaml
  - payments-testing-helmrelease.yaml
  - payments-testing-secrets.yaml
