apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: payments-testing-git
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: testing
  secretRef:
    name: git-credentials
  url: https://github.com/Fraguinha/payments
