apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-ci-rollout-reader
  namespace: payments-testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-ci-rollout-reader
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: github-ci
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-ci-port-forwarder
  namespace: payments-testing
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tailscale-ci-port-forwarder
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: github-ci
