apiVersion: v1
data:
    password: ENC[AES256_GCM,data:yicmrujoBSDJqFQnBrh188hujAcFRDQWNko2cwdCd7x+gAbrKuOCJvh/lDUre5idACVO+2i8H4Y=,iv:rXuUIgTuYilpqNj2SGvA7/9n3aGt5Z0rmQ9DOL/s6Lk=,tag:YKYjDVwsvUlL5R+wBwF3ZQ==,type:str]
    username: ENC[AES256_GCM,data:B2GQSf8VRX9H3+vG,iv:IBC9jDFLrnWebteAogrLGl4C9G52hIMGzI1qecgV8Nc=,tag:ketyV4VrXVvMamSmkFcDGQ==,type:str]
kind: Secret
metadata:
    labels:
        kustomize.toolkit.fluxcd.io/name: infrastructure
        kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: git-credentials
    namespace: flux-system
type: kubernetes.io/basic-auth
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeEFJKzFSdEdXdFAzT3Vk
            RG1rTEZMaHJEV29RVjJFN3IrVTBlVFpnS2w0CmFmWnl2Vkw2Qk9lQWhJTFp1OGc2
            YmQxdFQ0RTBDd3UvUUZEb2dRTTI0ZWMKLS0tIGd4WmJoY1ZQRDNGcEhhY0l5WHI1
            NHAzRVJUNkZqUkN4d2l3eG5iSGRJYkUKDs5nM+ULXFm6ny1KFyMF5xUYhtVCeIEX
            iwnjonV+zG7yIMst6/XYXHrQVKfscThKCMBC/kBI8+u22w8FepnE9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T20:57:59Z"
    mac: ENC[AES256_GCM,data:wq04S1wLbgKc0w2+Pm8WstGjK9LwA7YtkPe7vEElCWpL7jy6A5Tro2hA2glPE1Rlae0+JguEW77XEXdlPrL7bo9YsNl/oIK6wHLobADUU2r/P4KNMJ/mIIe8PoUSIvdpKnNJFLRFWIKf3AhJ5UA9yztF0g7XuyymMguAybAzmys=,iv:Fpf0pmhNjE5nZyCASSiltRXUSzurvM6xOP/HKabiHLM=,tag:SJC0oS3p6s+ZcBdWZMCInQ==,type:str]
    version: 3.13.1
