apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cnpg-backup-s3
  namespace: cnpg-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: cnpg-backup-s3
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: infrastructure/cnpg
        property: ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: infrastructure/cnpg
        property: ACCESS_SECRET_KEY
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: infrastructure/cnpg
        property: AWS_DEFAULT_REGION
