apiVersion: v1
kind: Secret
metadata:
    name: cnpg-backup-s3
    namespace: cnpg-system
type: Opaque
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:wkhJovMli/NGhX6j3ALQ5SEx3XiZ61q2UDA=,iv:k74Es7FhWp1CUS8B28o/Uy0L2AzxakFplxHJtBaw7EA=,tag:3ikgxmabUDIUPqJ7D7NeWw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:l+L/Y46qBnDdMBuyvT7zi7KAjFd/S8bkvE2do1xlF+Mb9qGYaQf1rFnDMkjmCsVzb4fYZU/MQ7tYGIqmoKgZPA==,iv:miKxx1k5wnsxTIIHf4PicwEgc9FwMbx3I7ApAwrTImQ=,tag:hOmWAwgHt6u2yhLpFyVqiw==,type:str]
sops:
    age:
        - recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwaDBERTZRQ2htbHkyTkhV
            WFJBRzY5dHVYTkMwejJiZldpK2RQenBna0E0CkpNaGk0MXBDOFljc3hjOTdMWDJN
            YXM0dlhWZ2xpRlJmSXo0VXFVY1JzcFkKLS0tIE02c05oekVlM2pPMmVNQzlaMHpU
            MDR0cE0wbTlSNmdGRUozTmQxOStsYTgK/Apc7yOCZQK2ZKAZMSxcjKNgAGwwYY2w
            XaB6rdttAuYCsdd5G55r6Pxmc/a19UhL79hxw67JxmUvJtEF7sv5SA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T09:22:25Z"
    mac: ENC[AES256_GCM,data:ZSR4+siHZm5V3TfP/hyiJD09GK/wGwtC6fUOhHBndcP/BlQJqQC4Aa/IOsWjN7CkQrC7efwATw+IX3+Zwsg78+P98WfxxltE+ikr1FTp0rwa5dysDOa7ahzGZ9Vh/7yqKJ2SX2GK+IHKWfIaLUvlQ7wgarTLJoMLflR2/S2ZAzs=,iv:tIb64ZAOr/lXzmr0rLG2W7X8m2Yjr5KC6ahYN0m51BY=,tag:lRU6trqiUO9Oz2sVP+vl0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
