apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    deployment:
      kind: DaemonSet
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        memory: 256Mi
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
    ports:
      web:
        hostPort: 80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true
      websecure:
        hostPort: 443
      minecraft:
        port: 25565
        exposedPort: 25565
        hostPort: 25565
        protocol: TCP
