apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio
spec:
  pools:
    - name: pool-0
      servers: 3
      volumesPerServer: 4
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
  env:
    - name: MINIO_PROMETHEUS_AUTH_TYPE
      value: "public"
  requestAutoCert: false
  podManagementPolicy: Parallel
