apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: payments-secrets
  namespace: payments
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: payments-secrets
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_URI
      remoteRef:
        key: applications/payments
        property: MONGODB_URI
    - secretKey: MOLLIE_API_KEY
      remoteRef:
        key: applications/payments
        property: MOLLIE_API_KEY
    - secretKey: WEBHOOK_SECRET
      remoteRef:
        key: applications/payments
        property: WEBHOOK_SECRET
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: applications/payments
        property: ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: applications/payments
        property: ADMIN_PASSWORD
    - secretKey: MAIL_USERNAME
      remoteRef:
        key: applications/payments
        property: MAIL_USERNAME
    - secretKey: MAIL_PASSWORD
      remoteRef:
        key: applications/payments
        property: MAIL_PASSWORD
