apiVersion: v1
kind: Secret
metadata:
    name: payments-secrets
    namespace: payments
type: Opaque
stringData:
    MONGODB_URI: ENC[AES256_GCM,data:PAyuQ3a66Kk89b3ax+SyIYR/Au1lccsHG+K/J2uWSGHz6YRiL338ghwhZ1lHJWp+LffZhbkdc60H7q6np2ADVYWVPofWsVbdSNNOFByvVspoGisgAJiKgqfU2gYhBjA=,iv:CWsnuFEIb3JerLkjmWGSMc3XFtjnZf3DLyjhNB4LKMo=,tag:/LKl5gZZAJwRKeDzy70CLw==,type:str]
    MOLLIE_API_KEY: ENC[AES256_GCM,data:txBHwr9ZBWtn3Bv8yasrAPYMW1Nb3EaYb7ZItYPZ2uu/7H4=,iv:WbZWkejJq76gMRPstZSwylcE2RHYkQxK/kPQDuTFDE4=,tag:PlRz0a7zw5uAJ5XhuauOPA==,type:str]
    WEBHOOK_SECRET: ENC[AES256_GCM,data:lI3m8jYNpkbc/n42UGcYphfwD8qgEFdWLMX3xOkdsXKu8413BsFoZ/5fe+SV+2TZE6Xel44u+p0TE/wx/KUnRA==,iv:a4Gs9+EfjZafAYm06tWgCaooC+H1+kKPcAp9L3O/eX0=,tag:yP7fQK87lIr43QzwwcDUYQ==,type:str]
    ADMIN_USERNAME: ENC[AES256_GCM,data:0pQI0JPvH8w4hQT+9qiuqnOLh/+8SeCqnBo36hwlHAmUY4F2hhU=,iv:dJBhyz3fyVhRI4xdpvQy2/JIWB8I6VSspRgBbBYDJPQ=,tag:nvTr9amNdaSUcHt2D06Eew==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:6DQWPwSMaFWh2woU+n2E7L64w9aUOsGv48xQkxZ3S0q2I8ozjmSRhkfAFTRO1VNjvi3N/zwSLC5lG/mT,iv:kyd08z7bUD9sXJaXX2QA4Mwcty+OQvnWmMVkw8j34zE=,tag:HdmSAY1FI2G78+ffAFvKBQ==,type:str]
    MAIL_USERNAME: ENC[AES256_GCM,data:zpzuHAXUgcmCMDm/hQyyWPBdQVc9APZ1,iv:RZPJfmG1GtmNbVeSiTAegaK+3i1lGs+7IoJYQ3heNL0=,tag:MehQ5DHFbteYACPFZ5sLIg==,type:str]
    MAIL_PASSWORD: ENC[AES256_GCM,data:SFIK2IkrDKmgy4bmnvM=,iv:zVSrcD+x9+gzB5JiuPcDeSTg7QmruTjc+lSxbVD1hwo=,tag:NghLjRWj3a23L1trhR/pHA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZHYyY2J4TzNpdmxCeVpv
            M3lVT0JrRktud3c2TkcwZnBZaCtpT3BjUUF3CmhHRFdlQWNNN0RKdDdlZkJ1NVB2
            cUVrUnlKMVNrNzBQaGEvKzZqOEQ1b3cKLS0tIDEweHk4SkVmQ2dFMVNRc3JoZkJk
            TEh2ZWhwRkd5NURLYmtWVE5RVDJKcWcK1xKCqsnDCC8AhAjzLMiwgXv1VmEvWIur
            E22ygctGDsVIU5mmkTjOSVX7/DxTg7PWV8V8T5Z2cOmBkBTJoJ/wXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T16:05:50Z"
    mac: ENC[AES256_GCM,data:j1YOA1s6b4a6JnyBYKMDu8opl9O8kBduS8hRl1B/QwDw63gocEQI95EZ5QYwPU9ckGYSMYl30TcQUSZwBqOauJadRTpMyWHLvzMdGNKIyeJ+WJ7+auXXDMqZjndhU1F116b52I8lRLReAWssIb26qmlwK7mZNAbtHKBLzcWjwnk=,iv:tbVzYVprBEeL2rjrb4rpKuIPASF09pX2PTqS4yd+oUQ=,tag:5COJpb7kTuQiuil/pt39Cg==,type:str]
    version: 3.13.2
