apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-tailscale
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 5m
  path: ./infrastructure/tailscale
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: tailscale-helmrelease
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
