apiVersion: v1
kind: Secret
metadata:
    name: tailscale-secrets
    namespace: flux-system
type: Opaque
data:
    oauth-client-id: ENC[AES256_GCM,data:DwdadFf6CYruz8+ybiASa3IqZp+ZTIqa,iv:I9Af0Rkt0HT2ioTUvd8Uf5lb9Q7T51voBa3QXvA4gAg=,tag:RB4LJutwPmSvCW5Ru40K0g==,type:str]
    oauth-client-secret: ENC[AES256_GCM,data:zrp58KNREWOXbtHMiGvK9AMAkbv/13D0A5gBpqQGkaM5UOL4roAxb17GdWUCFmHN24KdxJZSq9oXnnz/8+hw+/d6xfTwnrfbsTXPQquA8tZCW321,iv:Ux+WTvc7ir5wIJuRoNRM2kfLowrw5DNeJQC6s3QBoUo=,tag:DQcA1SImhSIiEeaAVBRL1A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMkZ5d2dNUWE2SkVhQm1O
            WnFWYXdySGYxaFVXZ3pJc0NqRDdncTZibURvCkNQSzNGTlczWEkwTThPQTE5b0Iy
            V0ZIVW9uUmFTdXl5K1FSZHRiOHBSZmMKLS0tIFFWbEZmQkp0ZjhZOGFtSEg3NmxT
            K29PMGUvSFdBQ1Fjb2x1WndzRXk5Y2MKCvybSVTzXh76Nj21a8P+HdChgnFeC0Bv
            aiRQecC4Cbu92ST/CrwnUVRZ4y9mQidj9ijFwC3J+dH0di38D8bc6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T20:58:00Z"
    mac: ENC[AES256_GCM,data:9jrA73hzAxcei8EpopzozG3Yu1xArvcRqtyD5FlbH+LhCxBa4SJnx9AJayarOu2WufcmOFlanYiqC4vkKiYfqpJWG0eSecI9YfP6v5CnDfIgtDSWtVQ8jT+uBJw4SjqShQDW2jecApR6VBeVeb1N8H2A7GX0ijP9uC3tyxZhElE=,iv:wT8hXb0gGEnum4QsexasRw6zv39Oyn0qSf7UG3W3OCI=,tag:Sg5Qfn9qKoPI5YeiPc2bSw==,type:str]
    version: 3.13.1
