apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1m
  releaseName: tailscale-operator
  targetNamespace: tailscale
  storageNamespace: tailscale
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 30m
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  valuesFrom:
    - kind: Secret
      name: tailscale-secrets
      valuesKey: oauth-client-id
      targetPath: oauth.clientId
    - kind: Secret
      name: tailscale-secrets
      valuesKey: oauth-client-secret
      targetPath: oauth.clientSecret
  values:
    proxyConfig:
      defaultProxyClass: default-proxy
    apiServerProxyConfig:
      mode: "true"
