apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tailscale-secrets
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: tailscale-secrets
    creationPolicy: Owner
  data:
    - secretKey: oauth-client-id
      remoteRef:
        key: infrastructure/tailscale
        property: oauth-client-id
    - secretKey: oauth-client-secret
      remoteRef:
        key: infrastructure/tailscale
        property: oauth-client-secret
