apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cmer
  namespace: flux-system
spec:
  interval: 1m
  releaseName: cmer
  targetNamespace: cmer
  storageNamespace: cmer
  install:
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 30m
  chart:
    spec:
      chart: ./chart
      sourceRef:
        kind: GitRepository
        name: cmer-git
      reconcileStrategy: Revision
  values:
    ingress:
      externalDnsTarget: ${PUBLIC_IPS}
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: all
              spec:
                template:
                  spec:
                    topologySpreadConstraints:
                      - maxSkew: 1
                        topologyKey: kubernetes.io/hostname
                        whenUnsatisfiable: DoNotSchedule
                        labelSelector:
                          matchLabels:
                            app.kubernetes.io/instance: cmer
