apiVersion: v1
kind: Namespace
metadata:
  name: cmer
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-cpu-limit
  namespace: cmer
spec:
  limits:
    - default:
        cpu: 1000m
        memory: 1Gi
      defaultRequest:
        cpu: 10m
        memory: 64Mi
      type: Container
