apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-secrets
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: external-dns-secrets
    creationPolicy: Owner
  data:
    - secretKey: PTISP_A50PASSOS_DOMAINS
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_A50PASSOS_DOMAINS
    - secretKey: PTISP_A50PASSOS_EMAIL
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_A50PASSOS_EMAIL
    - secretKey: PTISP_A50PASSOS_HASH
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_A50PASSOS_HASH
    - secretKey: PTISP_FRAGUINHA_DOMAINS
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_FRAGUINHA_DOMAINS
    - secretKey: PTISP_FRAGUINHA_EMAIL
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_FRAGUINHA_EMAIL
    - secretKey: PTISP_FRAGUINHA_HASH
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_FRAGUINHA_HASH
    - secretKey: PTISP_LIVINVICTA_DOMAINS
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_LIVINVICTA_DOMAINS
    - secretKey: PTISP_LIVINVICTA_EMAIL
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_LIVINVICTA_EMAIL
    - secretKey: PTISP_LIVINVICTA_HASH
      remoteRef:
        key: infrastructure/external-dns
        property: PTISP_LIVINVICTA_HASH
