apiVersion: v1
data:
    PTISP_A50PASSOS_DOMAINS: ENC[AES256_GCM,data:WhERoFGfPKlGYP1rh1v/ZI4inNQchFR5FnxP8xrm+L3HIrsi,iv:sAl3ajKNSFtvLs0FNZ7nBdHLnh41Z4DhMN9sVPKjQ9g=,tag:s4GTOVVssDRdndBngo2L1A==,type:str]
    PTISP_A50PASSOS_EMAIL: ENC[AES256_GCM,data:mWdBTP7Q9hcfIUTmh97VfhiHvV0QudQa9xpBgA==,iv:yPp67ghE0cX08RwuX2Xc2Jy12d/qLUgN6bDKccqOSgI=,tag:Cru6dDUicnjpIbvFgGfu/A==,type:str]
    PTISP_A50PASSOS_HASH: ENC[AES256_GCM,data:pxhqnRuJFql25DZ8+4OWr7gquho0IJA6jVByu1YeKP5QRJV8j8K06/nO5LE=,iv:vKD5AWyM1WND2/uj5UDERjL5X85NrMZ/1c1Po+DHwUs=,tag:f5AiMfRkfg9TD8h+UjcvkQ==,type:str]
    PTISP_FRAGUINHA_DOMAINS: ENC[AES256_GCM,data:TeKmg2JAVqf7toEkoMFQfHK8xVU=,iv:R/fhxHJm3Kd2YfXeafMkAjdt8rtbQcDigop2mlmlvmw=,tag:rtjRv4eCksikNNtdC42jgg==,type:str]
    PTISP_FRAGUINHA_EMAIL: ENC[AES256_GCM,data:SbP+VrwYofUAiB/Tt6bozOx9hW4/fOKGcmogDhwpbMFr4eVDF9S22A==,iv:Mrv8n5rgYWoLGbXz3Tm8fRHFdszOK6jHPwl6qF/SbMc=,tag:WkNCdNVXQ1HklNCJZPTgCQ==,type:str]
    PTISP_FRAGUINHA_HASH: ENC[AES256_GCM,data:NpzzgZMFy8mHPnhsJV2xaRX+uWt5bMv4JY2JJ61OtQhRH7lQpqSUgjGjhMw=,iv:oi+b5JDoGY4tExXQz/jJUaxpd+hSP8ufxOMFxk3FZe8=,tag:2VweLzxmb4XYg89kuftI8A==,type:str]
    PTISP_LIVINVICTA_DOMAINS: ENC[AES256_GCM,data:O+oWxQOyoJx5F43rqX7jBunrLLCwRRgI8PaaRCoA3okecO72CCj+Sw==,iv:m/MG/ORQS5r4xDljFSIjEKXx3cga5s0IAVzo3S/oJEA=,tag:JFg8vtB+5UC7A3KNDYuTKA==,type:str]
    PTISP_LIVINVICTA_EMAIL: ENC[AES256_GCM,data:jMaj43Y2G4jZ/mBS6hmuAsKQ0PPPVyYsWTgjlQ==,iv:+5tC/HAR9MM7I8t+QzBZ+ddCRqB1w/TDYl9F5Wpepq4=,tag:ky1lU5UhibJol4RyaR8jgw==,type:str]
    PTISP_LIVINVICTA_HASH: ENC[AES256_GCM,data:cOwupu2hj98i4RvHgUGIUGrs97og8vIfvUgkE3/U/6p8wI/xmL46oMDa9mM=,iv:Cx+4WI5s+h7/NszxLhFqSM9cBqjr50tCtxQmueLV7lE=,tag:UT0Kg3FVXto++yaMy0qmEg==,type:str]
kind: Secret
metadata:
    name: external-dns-secrets
    namespace: external-dns
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbWszR3B5TjVxZTJXQ24r
            cUY3OUtWS2FBMmtGMXFheVlVa3R4azJ6a1drClcxdm9YRGVyM21tdXZtNEtDdkwz
            Ny9tQUxzZ0RGT1EyVDJsaG1LWC9NTGMKLS0tIEN0L1VWR1Y2dnc2WHh4UStyRHhL
            NDNsMEgzRGpKTVlRV3VSMTU4UytZMXcKJU77VwC9zJqKB9jLtiBSpINeAG3o/tbY
            vu5XTUfxRgbqcj3RkL2kqbmronqolZBNyyporJQVkYSh1xGGXhz3aA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T20:57:59Z"
    mac: ENC[AES256_GCM,data:FeOakDBiW6cG7pXRcrW3SmisDRS9pZsGwD8YJwYOJeaZ88wY6WD1hzBp5iq1qNe5j1o4wQG/Tl6daMuF01awO4uPCrEzjhYdY4oVzCpjSUxgsuIc93KOkP7URPxc+DskBlT4L6ZW1SlOdZukRZEdOx4CzQ8u/IBl1A3ZFEyj6VU=,iv:8+7Yylqmjrlm4L4hp73r3vdb2qJ92t1uXPKQqHX37Qo=,tag:wh7zlNS2KeXA3a6MBYSLew==,type:str]
    version: 3.13.1
