apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - vm-source.yaml
  - monitoring-secrets.sops.yaml
  - vm-helmrelease.yaml
  - grafana-tailscale-ingress.yaml
