apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: loki
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: grafana
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  targetNamespace: monitoring
  values:
    loki:
      auth_enabled: false
      storage:
        type: s3
        s3:
          endpoint: http://minio-minio.minio:9000
          region: us-east-1
          s3ForcePathStyle: true
          accessKeyId:
            valueFrom:
              secretKeyRef:
                name: minio-minio
                key: rootUser
                namespace: minio
          secretAccessKey:
            valueFrom:
              secretKeyRef:
                name: minio-minio
                key: rootPassword
                namespace: minio
        bucketNames:
          chunks: loki-chunks
          ruler: loki-ruler
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: s3
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
      ingester:
        chunk_encoding: snappy
      tracing:
        enabled: true
      querier:
        max_concurrent: 4
    deploymentMode: SimpleScalable
    backend:
      replicas: 3
      persistence:
        enabled: true
        size: 4Gi
    read:
      replicas: 3
      persistence:
        enabled: true
        size: 4Gi
    write:
      replicas: 3
      persistence:
        enabled: true
        size: 4Gi
    gateway:
      replicas: 3
    minio:
      enabled: false
    singleBinary:
      replicas: 0
    ingester:
      replicas: 0
    querier:
      replicas: 0
    queryFrontend:
      replicas: 0
    queryScheduler:
      replicas: 0
    distributor:
      replicas: 0
    compactor:
      replicas: 0
    indexGateway:
      replicas: 0
    bloomCompactor:
      replicas: 0
    bloomGateway:
      replicas: 0
    chunksCache:
      resources:
        requests:
          memory: 512Mi
