apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: minio-secret-reader-role
  namespace: minio
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-secret-reader-binding
  namespace: minio
subjects:
- kind: ServiceAccount
  name: helm-controller
  namespace: flux-system
roleRef:
  kind: Role
  name: minio-secret-reader-role
  apiGroup: rbac.authorization.k8s.io
