apiVersion: v1
kind: Secret
metadata:
    name: monitoring-smtp-secrets
    namespace: monitoring
type: Opaque
stringData:
    smtp-password: ENC[AES256_GCM,data:I5SLAA3o8gVQ+Cx02R59BqpglA==,iv:z72edIaY2p4w1G79uPRHk3+sLwiBapPa3/VE7TtoyTU=,tag:IIm1LdXen6TxrUYs/aqVXw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzR2pnUGkvRWhoUWV2Mmlr
            RXJtUGs2ajFYNVN4c1liV0YwM2p0TGFnWVY0ClhwRmlnYlFVV3J3OG1YU25nZmo3
            RWtTSnFvV2VLNWhXK1hYUEh6bzd5a28KLS0tIGkxN0RHN3VpaWhWNDJVb09ZSCtr
            WnhWRU56RThrMnRXYk42YlM0RG5TNW8K/csPgsLMlO5evodpJhEkpXAE8wlhWix9
            CTo0tCpFablmH1lFvPbTsJNVBwR1XFI6JUvBUgWLnsI4OtB761okIw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-22T17:32:53Z"
    mac: ENC[AES256_GCM,data:PE0S4hio/0h4ccARbOmIZ7wdL70zG1BfPsC34IJE6fX1dcn6kE7qHXSLsfKm9hRmjE2dil4I3Y2BTH0hWqER+NKrPKidKkEuUY2MXxu7LYtUy+e+Y2sLsRYoAxAG3GDaW4qivxLlFxzVZ+Ga3s317IgFftKKDUNdi0UP/ngWneg=,iv:MIPdOOUeMW5TLS2cQ4JGsWVhCPVeszB+72LfyuTa4H0=,tag:nFCVqk1GuKO4jHLCH9MQwA==,type:str]
    version: 3.13.1
