apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: flux-system
spec:
  interval: 1m
  releaseName: vms
  storageNamespace: monitoring
  targetNamespace: monitoring
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoriametrics
  values:
    victoria-metrics-operator: {}
    syncJob:
      image:
        pullPolicy: Always
    grafana:
      enabled: true
      persistence:
        enabled: true
        storageClassName: longhorn-single
        size: 1Gi
      deploymentStrategy:
        type: Recreate
        rollingUpdate: null

    vmsingle:
      enabled: true
      spec:
        storage:
          storageClassName: longhorn-single
          resources:
            requests:
              storage: 30Gi

    vmagent:
      enabled: true
      spec:
        replicaCount: 1
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi

    vmalert:
      enabled: true
      spec:
        replicaCount: 1
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi

    alertmanager:
      enabled: true
      spec:
        replicaCount: 1
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 10m
            memory: 64Mi
        secrets:
          - monitoring-smtp-secrets
      config:
        global:
          resolve_timeout: 5m
          smtp_from: "joao@fraguinha.com"
          smtp_smarthost: "smtp.mail.me.com:587"
          smtp_auth_username: "joao@fraguinha.com"
          smtp_auth_password_file: "/etc/vm/secrets/monitoring-smtp-secrets/smtp-password"
          smtp_require_tls: true
        route:
          receiver: email
          group_by: ["alertname", "namespace"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          routes:
            - receiver: "null"
              matchers:
                - severity = none
              continue: false
        inhibit_rules:
          - source_matchers:
              - severity = critical
            target_matchers:
              - severity = warning
            equal: ["alertname", "namespace"]
          - source_matchers:
              - alertname = InfoInhibitor
            target_matchers:
              - severity = info
            equal: ["namespace"]
        receivers:
          - name: "null"
          - name: email
            email_configs:
              - to: "joao@fraguinha.com"
                send_resolved: true
    kube-state-metrics:
      enabled: true
      livenessProbe:
        timeoutSeconds: 10
        failureThreshold: 5

    prometheus-node-exporter:
      enabled: true
      dnsPolicy: Default

    defaultRules:
      enabled: true
      groups:
        etcd:
          enabled: false
        kube-scheduler.rules:
          enabled: false
        kubernetes-system-scheduler:
          enabled: false
        kubernetes-system-controller-manager:
          enabled: false

    kubeScheduler:
      enabled: false

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    extraRules:
      flux:
        groups:
          - name: flux-alerts
            rules:
              - alert: FluxReconciliationFailure
                expr: |
                  gotk_reconcile_condition{status="False",type="Ready"} == 1
                for: 10m
                labels:
                  severity: warning
                annotations:
                  summary: "Flux {{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} failing to reconcile"
                  description: "Flux {{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} has been failing reconciliation for more than 10 minutes."
