apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-helm-values
  namespace: flux-system
data:
  values.yaml: |
    victoria-metrics-operator: {}
    syncJob:
      image:
        pullPolicy: Always
    grafana:
      enabled: true
      persistence:
        enabled: true
        storageClassName: longhorn-single
        size: 1Gi
      deploymentStrategy:
        type: Recreate
        rollingUpdate: null
      plugins:
        - victoriametrics-logs-datasource
        - victoriametrics-metrics-datasource

    vlsingle:
      enabled: true
      spec:
        retentionPeriod: 30d
        storage:
          storageClassName: longhorn-single
          resources:
            requests:
              storage: 10Gi
    vlagent:
      enabled: true
      spec:
        k8sCollector:
          enabled: true
          ignoreFields:
            - _time
            - _stream
            - _stream_id
            - kubernetes.container_name
            - kubernetes.pod_name
            - kubernetes.pod_namespace
    vmsingle:
      enabled: true
      spec:
        storage:
          storageClassName: longhorn
          resources:
            requests:
              storage: 30Gi

    vmagent:
      enabled: true
      spec:
        replicaCount: 1
    vmalert:
      enabled: true
      spec:
        replicaCount: 2
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vmalert
    alertmanager:
      enabled: true
      spec:
        replicaCount: 2
        topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: vmalertmanager
        secrets:
          - monitoring-smtp-secrets
      config:
        global:
          resolve_timeout: 5m
          smtp_from: "joao@fraguinha.com"
          smtp_smarthost: "smtp.mail.me.com:587"
          smtp_auth_username: "joao@fraguinha.com"
          smtp_auth_password_file: "/etc/vm/secrets/monitoring-smtp-secrets/smtp-password"
          smtp_require_tls: true
        route:
          receiver: email
          group_by: ["alertname", "namespace"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 4h
          routes:
            - receiver: "null"
              matchers:
                - severity = none
              continue: false
        inhibit_rules:
          - source_matchers:
              - severity = critical
            target_matchers:
              - severity = warning
            equal: ["alertname", "namespace"]
          - source_matchers:
              - alertname = InfoInhibitor
            target_matchers:
              - severity = info
            equal: ["namespace"]
        receivers:
          - name: "null"
          - name: email
            email_configs:
              - to: "joao@fraguinha.com"
                send_resolved: true
    kube-state-metrics:
      enabled: true
      livenessProbe:
        timeoutSeconds: 10
        failureThreshold: 5

    prometheus-node-exporter:
      enabled: true
      dnsPolicy: Default

    defaultRules:
      enabled: true
      groups:
        etcd:
          enabled: false
        kube-scheduler.rules:
          enabled: false
        kubernetes-system-scheduler:
          enabled: false
        kubernetes-system-controller-manager:
          enabled: false
        kube-prometheus-general.rules:
          enabled: false

    kubeScheduler:
      enabled: false

    kubeControllerManager:
      enabled: false

    kubeEtcd:
      enabled: false

    extraRules:
      flux:
        groups:
          - name: flux-alerts
            rules:
              - alert: FluxReconciliationFailure
                expr: |
                  gotk_reconcile_condition{status="False",type="Ready"} == 1
                for: 10m
                labels:
                  severity: warning
                annotations:
                  summary: "Flux {{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} failing to reconcile"
                  description: "Flux {{ $labels.kind }} {{ $labels.exported_namespace }}/{{ $labels.name }} has been failing reconciliation for more than 10 minutes."
