apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: flux-system
spec:
  interval: 1m
  releaseName: vms
  storageNamespace: monitoring
  targetNamespace: monitoring
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    timeout: 30m
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
    timeout: 30m
  valuesFrom:
    - kind: ConfigMap
      name: vm-helm-values
      valuesKey: values.yaml
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      sourceRef:
        kind: HelmRepository
        name: victoriametrics

