apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: stand-backend-image
  namespace: flux-system
spec:
  image: fraguinha/stand-backend
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: stand-backend-policy
  namespace: flux-system
spec:
  digestReflectionPolicy: Always
  interval: 1m
  imageRepositoryRef:
    name: stand-backend-image
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: stand-frontend-image
  namespace: flux-system
spec:
  image: fraguinha/stand-frontend
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: stand-frontend-policy
  namespace: flux-system
spec:
  digestReflectionPolicy: Always
  interval: 1m
  imageRepositoryRef:
    name: stand-frontend-image
  filterTags:
    pattern: '^latest$'
  policy:
    alphabetical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: stand-update-automation
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: stand-git
  git:
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
    push:
      branch: main
  update:
    path: ./chart
