apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
spec:
  interval: 5m
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: ">=0.40.0"
      sourceRef:
        kind: HelmRepository
        name: strimzi
        namespace: flux-system
