apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kafka
  namespace: flux-system
spec:
  install:
    crds: CreateReplace
    remediation:
      retries: 3
    createNamespace: true
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: kafka
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: kafka
        namespace: flux-system
  interval: 1h
  targetNamespace: kafka
  values:
    image:
      repository: bitnamilegacy/kafka
    replicaCount: 1
    controller:
      persistence:
        storageClass: longhorn
        size: 4Gi
    zookeeper:
      replicaCount: 1
