apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tor-relay-git.yaml
  - tor-relay-kustomization.yaml
  - tor-family-secret.sops.yaml
  - tor-relay-image-automation.yaml
