apiVersion: v1
kind: Secret
metadata:
    name: tor-family-secret
    namespace: tor-relay
type: Opaque
data:
    id: ENC[AES256_GCM,data:k32uTiIFqH9RfZCTrEraAVqGkzH2u0/T8DiauwPiHOwHpOW9xrGZlhRhYxgw1aRRkAxGF8+7K50RXdo0,iv:IuZ0fQQwCqvgYREn9X2E0dft+Oc0hQl+PGXa4Sv25Zg=,tag:rtNabraeVq3DJ8oFqJzyNw==,type:str]
    secret_family_key: ENC[AES256_GCM,data:ifwIBDvFf+aftxsvKnZSpGSWhEzeL9Ppvve/Hx4U+Bi5sqaYuiLj87qqCN2ief1c5SLWAT8FTaEOwuCru9ilk0dVztfb4Hid6KNiboPAbQl6mKhKf+dhAY3R9TT2db0u85NsOLt0JYngraWzR6505TyU0uGII6SHlCrfkMWngiQ=,iv:LURiKwq1oki5B6FvS5hUgX0LHl39Oa7AbNLbufm+hzs=,tag:UkC/9rcJtnJz5IBr/pl/TA==,type:str]
sops:
    age:
        - recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUkJ2VEFhQndiN3ZvRkFS
            WnM5MzBjWlNIZ0xvRFpEYm5mV1VxOCsrUGdjCjQ2UEg4c0I0T0hkNisraDlNR3Ry
            YlA5bEt4T2pwVyt2UlpTbDV2OHM0cDAKLS0tIE9NSmFqQUsvZXZyTlRnUCtaZzh1
            Wm52bWpURUJ4M1UzQ0lvQzZBYS9sanMKP32gC4gel/gDG1b//Zy/YyWO+0IzpE87
            RoZloM9TOk4yrq9WivsSrhh8in2TwNxTpg2fB88oj2FkS1nwWTYqmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T20:37:32Z"
    mac: ENC[AES256_GCM,data:eznsE851mqDh3lcA9KRK2nUNpjountUquxjHidcoMry7luIsgCpM6KCxpb1lgCIZFgYVmzRiqjTFT7r0otBVdZIOFgKC5e/JTMIdZFIynO4F1SuKoqFrpdFJgAgzJQ8qe0zfbkHub1j0MKgBPatrBOREMoAOZidmJQa5vsEa9Wg=,iv:Dh2ACAIJDytdxYLN6XlXLr2PZEbg9mkJOkjHFVCYXro=,tag:MfDt6GavslIBJhXVcGBctg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
