apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  interval: 24h
  chart:
    spec:
      chart: operator
      version: '7.0.0'
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
  install:
    createNamespace: true
