apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - middleware.yaml
  - auth/
  - configmap/
  - deployment.yaml
  - tmux/
  - ingress.yaml
  - pvc.yaml
  - service.yaml
  - shell-secrets.sops.yaml
