apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shell-secrets
  namespace: shell
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: shell-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_USERS
      remoteRef:
        key: applications/shell
        property: AUTH_USERS
    - secretKey: VAPID_PRIVATE_KEY
      remoteRef:
        key: applications/shell
        property: VAPID_PRIVATE_KEY
    - secretKey: VAPID_PUBLIC_KEY
      remoteRef:
        key: applications/shell
        property: VAPID_PUBLIC_KEY
    - secretKey: host_key
      remoteRef:
        key: applications/shell
        property: host_key
    - secretKey: host_key.pub
      remoteRef:
        key: applications/shell
        property: host_key.pub
    - secretKey: fraguinha_GH_TOKEN
      remoteRef:
        key: applications/shell
        property: fraguinha_GH_TOKEN
    - secretKey: fraguinha_id_ed25519
      remoteRef:
        key: applications/shell
        property: fraguinha_id_ed25519
    - secretKey: fraguinha_id_ed25519.pub
      remoteRef:
        key: applications/shell
        property: fraguinha_id_ed25519.pub
    - secretKey: carolina_GH_TOKEN
      remoteRef:
        key: applications/shell
        property: carolina_GH_TOKEN
    - secretKey: carolina_id_rsa
      remoteRef:
        key: applications/shell
        property: carolina_id_rsa
    - secretKey: carolina_id_rsa.pub
      remoteRef:
        key: applications/shell
        property: carolina_id_rsa.pub
