apiVersion: v1
data:
    DATABASE: ENC[AES256_GCM,data:QISymM0yRY6sIX6EAZp6TENAul+ht0n55x5kBfyT1IPdW5uuESzsmO4tb68v43MnUaKDD27a9t7OL1eq9d183PKx4c4hlu0b27n3nAmOk8DMNpjZdGCsVC7XDPXbE1qi3V3s94avBOYN9mc0ginNbKi7MI7+AkVEkq8jd0dEiHA=,iv:GbrQ8i3vyJOnUz6S8VtD+j4DEZT6ao/6PUbDXIGNZQM=,tag:vvQtQv7xvxlA6GA6Fo+Lmg==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:X5Q43+6N7emYO+U+dxoQKw2lRysny/gARXEqYg==,iv:N0G2hVS5uSuDWUN9S9DpDxCTQeMd6Kacv+gOpgx8lOI=,tag:ros/BT+PaC12w3IMrAaH8w==,type:str]
kind: Secret
metadata:
    name: a50passos-secrets
    namespace: a50passos
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVnRYQ2lrYmljd2llaVNB
            MjhuNEJ5bmV3L3N5Vm84ckNvTCtVUGtpRFFrCjE5TUprRFZiNG5reXRwUStwZktL
            L1RabnRpMk5RbkIxUEwyd1pUMUdKYTQKLS0tIGlJK092dGFmcDNTbC9GWERWcEJn
            WTNCNy9xTjY3N0pEa0thUXhOWGtBOVEKV1Jr3BncnA1CH553sSdYoF9cVkrCVc+x
            NIuBFQ5bJD60fEAmoH8kwMSezqKud2noFR013ZLt3oykTu393oQMVA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T20:58:00Z"
    mac: ENC[AES256_GCM,data:bMPs/Jg4CxCSeqGcZtKke2WFnMf9YsV6/zyhzmlTFqDxz9yRerLVOFrLQOTHMQPyvGBF2sfRrFFkfp92f7AcZdaVFXTisZ+WTV9EHVU66VieHpzbJw6fzV1hENOBmVMgdkGLvRRusoaY0mgU+era/mE+rwzDvaenDWmmaWt9ANo=,iv:bszxiof5JogzjNHRDEtCBDlRa6bhN77qvlEFN+CV5P0=,tag:yBOfxmTVtpDl4h4m8bJGWA==,type:str]
    version: 3.13.1
