apiVersion: v1
data:
    DATABASE: ENC[AES256_GCM,data:SiCRrPdttzT5DOOWJmXE0+llIPdwjQxWQVKs/I09g2bqH5JOwDwYZIRcZa5KuRCN5tmJ5VODRhnLJI/b+CaSkAUaNpakcmqskbFp9PHF4rHLR77EXUPWtDcKd8HIKEx8o9XIBeWmjzzm8al7NBqLgGnb+l9UIzfirClrARg/H/A=,iv:j0Ta9TNw1DtSTCFCNcGIpibSovoBh8zYyeNeh6SM2nA=,tag:Gf5PRLAIilAAcnjZCyykrw==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:F/MPlVBjFzBvy/Nj9l5Y97GvIiZXimW7xIRnqA==,iv:HEtb4omQ3S/le9O8z3x5S2kgexkDnRA8R8uGxeOj5kk=,tag:v0tJjFdwTD5WTo5HG5mM7Q==,type:str]
kind: Secret
metadata:
    name: a50passos-secrets
    namespace: a50passos
type: Opaque
sops:
    age:
        - recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkRWVoQUZFTDJiSUdRaHFj
            SVBlL0dTLy9nKzVEeGc3bUVORlp0b1dGVXdRCktGTWxJNnAwNm5BWXFueWZ6U0lD
            KzZ3Q3RWMnphY284VzVoQjVFU1dWYU0KLS0tIE1BdFBobkxSRFpkc0swWXJtVkZN
            VmNIWjFTdUVDaWRlSEF5OC9xZ0JlMEUKG7JyF87vXjncGPU79wP85sW3cWfp+IeH
            SQkWmIBxh87vnPovJemPXx/D044XV2VJEs9rbk/LLc/SkGVSo2RDRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T15:05:51Z"
    mac: ENC[AES256_GCM,data:DC+hdMFwwflRE5uXT0eSw6MOQR8zwh6qFepiZqbn03Jf6Y7JYsUtc1FAJaiP9fvO4/86Lfu+FP/LBMcNj/tCFJy/cjcOiSJ/Cpojr2n0x0zY/YpgRarp9JBXNFVg8I975QerTh/uMdcMajjgn0BXabdXwhXvs+cDGPWamNn4wxA=,iv:SGHk5RvXLpiNi4mrpB9aj2tspmmJUBq79rcInI3Bw8o=,tag:kx1pbb8izovA1L6EgNEJpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
