apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-a50passos
  namespace: flux-system
spec:
  interval: 1m
  timeout: 30m
  path: ./applications/a50passos
  prune: true
  wait: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: a50passos
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-longhorn
    - name: infra-cert-manager
    - name: infra-external-dns
    - name: infra-traefik
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: external-dns-targets
        optional: true
