apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: external-secrets
  namespace: vault
spec:
  authentication:
    path: kubernetes
    role: vault-admin
    serviceAccount:
      name: vault-admin
  path: kubernetes
  policies:
    - external-secrets
  targetServiceAccounts:
    - vault-auth
  targetNamespaces:
    targetNamespaces:
      - external-secrets
  audience: vault
  tokenTTL: 3600
