apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: livinvicta-git
  namespace: flux-system
spec:
  interval: 5m
  ref:
    branch: main
  secretRef:
    name: git-credentials
  url: https://github.com/fraguinha/livinvicta.com
