apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: livinvicta-secrets
  namespace: livinvicta
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: livinvicta-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE
      remoteRef:
        key: applications/livinvicta
        property: DATABASE
    - secretKey: GOOGLE_CLIENT_ID
      remoteRef:
        key: applications/livinvicta
        property: GOOGLE_CLIENT_ID
    - secretKey: GOOGLE_CLIENT_SECRET
      remoteRef:
        key: applications/livinvicta
        property: GOOGLE_CLIENT_SECRET
    - secretKey: SECRET
      remoteRef:
        key: applications/livinvicta
        property: SECRET
