apiVersion: v1
data:
    DATABASE: ENC[AES256_GCM,data:xhSC5ljYfzv/XDRJ6a2Gu5NEluGcxyP8P8u3Ssa09ciZ4Megk18torgXkMTEPUqVAPU9VQrq8ATEDPphehxzukcjQudjzv3CcYPMHZhtieau82Y8bOQaQptcBRLK6/wejCIkpijjJW8NbztqZ0WACI9Cm2HlKVSUUTDYCqE1jhzAXZsRpQU5Q9NzqDB3/ERqpXV/wifMdX1Dw8Sn,iv:JGI1twv5v3C7kldqyoc7mUezk/WxfFMh/Gx+LWknyFI=,tag:FQciIRvR1yn76nu9O9BnRg==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:UTa0KhxfOhOJZVjQf81jhwaLT8YKbxerM6p8j+DogathtXnoDA2qUAGFK19gCzHu6rJcycQu5bfMos5GDJVjmdIxuGJjUcC1f85VV1vkOhcaLrByCIgu50T6XuAIqU7O,iv:J6UZg5fA+JPqIX0E1NDdc6z91hHNSIjckmBjpGTlDU8=,tag:EQedLmQZHeoF8IdZ30YpPQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:BKSgaPpgxnvKvC0t8HvUgibNwA+ktZ6ft1Jd2zUExamyEwJMgyrxTbg7LhMZrYy2,iv:Hwe7lJYA6Mnj6Ul4qGfRM/iOhQAGMUHcJrd8+IJs92o=,tag:1dR9hgfNxtd+npnvTNFTYw==,type:str]
    SECRET: ENC[AES256_GCM,data:B/XikB1oncBheGYcPutsEPgRvfg=,iv:BxwrJkCm+C6HdoszwBfM6FF/d0aryuw4q+/unUkbnqM=,tag:eXoJDG0kIjMOVcqbt8TC4g==,type:str]
kind: Secret
metadata:
    name: livinvicta-secrets
    namespace: livinvicta
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWnZ0eFRoYUtlejRYK0JN
            YWlnaExJbjBVK2RsUE50STVkbEI4STZGMHg0CkVnYUJySHR3MTllNXduc1dYZHd3
            WDB0Y3pNcUF0U0VEcVBJei9ISm1weVEKLS0tIFhHbXFyVzYwSlE1ekZvQTZicVI2
            WE9Sa2p0eDM2eEhNMW9LYTlIZzlDWXcKmyX7dVe/btNi4NL5n1rqyg97CQJCMlNE
            alrVgHaI2pgkrhIxdkkqgyUEr9l6ObT9GeMm3fo5nv0LtVMeUink4A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-16T20:58:00Z"
    mac: ENC[AES256_GCM,data:zd2vRqbmxNQ1S0weoWE+xcfIqe7DinK+uga01NIhVe0SyO0KZDryX016UXw0uIAZScKuFIfcg9CJrBz7pY67u1IePT2WmsMkWXayFfPhpy2t6q9OFu+ALHLHWy5l3LfatcGYhS8xY6qwsvAHRUrh+xhwTzZ7sjKQW+PCQ7YYLpI=,iv:EUF6+nWmozXR9+3aw50MeIGPdtjGfRQeGsadmIx7nV8=,tag:RhRL6I/BZ2BJHWTjhjvBrg==,type:str]
    version: 3.13.1
