apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager/flux.yaml
  - cert-manager/config-flux.yaml
  - external-dns/flux.yaml
  - kured/flux.yaml
  - longhorn/flux.yaml
  - monitoring/flux.yaml
  - tailscale/flux.yaml
  - traefik/flux.yaml
