apiVersion: v1
kind: ConfigMap
metadata:
  name: shell-tmux-dotfiles
  namespace: shell
data:
  .gitconfig: |
    [user]
      name = Fraguinha
      email = joao@fraguinha.com
      signingkey = /root/.ssh/id_ed25519.pub
    [gpg]
      format = ssh
    [commit]
      gpgsign = true
    [tag]
      gpgSign = true

  .tmux.conf: |
    set -g extended-keys on
    set -g extended-keys-format csi-u
    set -g mouse on
    set -s set-clipboard on
    set -g allow-passthrough on
    set -g update-environment "COLOR_SCHEME"
    set-hook -g client-attached 'run-shell -b "/opt/bin/update-theme"'
    set -s user-keys[0] "\033[15;3~"
    set -s user-keys[1] "\033[17;3~"
    bind-key -T root User0 run-shell -b "/opt/bin/update-theme dark"
    bind-key -T root User1 run-shell -b "/opt/bin/update-theme light"

  update-theme.sh: |
    #!/bin/sh
    cp /usr/local/lib/node_modules/@earendil-works/pi-coding-agent/dist/modes/interactive/theme/$${1:-$${COLOR_SCHEME:-dark}}.json /root/.pi/agent/themes/system.json
