apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-home-assistant
  namespace: flux-system
spec:
  interval: 5m
  path: ./applications/home-assistant
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infra-longhorn
    - name: infra-cert-manager
