apiVersion: v1
kind: Secret
metadata:
    name: hermes-agent-secrets
    namespace: hermes-agent
type: Opaque
stringData:
    COPILOT_GITHUB_TOKEN: ENC[AES256_GCM,data:eKujM8LBShTsxntIxZIUzPdcsYv0FM9KnDeEt8NDL/b642RW86N/YQ==,iv:bYr84FKwE9/o3a7lUyxA+csAxoh4RatfB2ZcheStQz8=,tag:xdGoReDwxHliLJyh0AIZlQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:EPqCFv3QhiUUDQm0tnKdl0anSlaCmk0aJnCBBxlTjuKtsn3kSD7dp5pGlUN+q/3KALI2Aa3ClbSRIDie1m6i8RQz+9DZqH6sB6fXKtg5wTM5x1UU5VJqve9mM6wU,iv:QFGzRRAriLFTf5awe2Am1mYzuW+I8h6XzRnssB+mCZE=,tag:WPirzN/64nZgAgbmgN/8kg==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_USERNAME: ENC[AES256_GCM,data:0D9bizJ0dJeA,iv:EPCbUCK/c2WIPl3BneQJNMLhP2x7o0GWXyI6468Lic4=,tag:25yNb/uLrR5enjobFicuww==,type:str]
    HERMES_DASHBOARD_BASIC_AUTH_PASSWORD: ENC[AES256_GCM,data:COfeWWb7CN1zd5JdAAu+LdyDD/0iCzBjvJ0XIXO0VxI=,iv:h3al0P1nXJO7vtr0pRebzAfAJ51xw9TnngSszV8BMPc=,tag:78xDk8iBFfIrHS2Rfe4Cxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Mis0U3RvWTNlbGFPVzhU
            MnRsR2xyU0ZycC9IQnFiMzNxUXlQY1B0b1JzClB5VlpyWGw0bzg5bjBqMExpTmVr
            ZEl4ZDAveFZSYkp3T0YxRUc0eVl2bVkKLS0tIGp0YTArQTlVTnRMUEkyMWlPOWJy
            UEc3a1BKQUdZMG9CeVBSSEdKck91RDQKQ3kiGfL4JXGXdyMVaz+evAKKjXEsCoyc
            bP+8RZmlbvEUzJP5rIBVQ8Lr5ewLQS+gFW9qCbVsVNgR0cjFfNLd2Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age10mxggdwhskxfupacndxft6ss5x4ay4l68ku83c4kgevwwlj6tessfw490z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-26T13:53:57Z"
    mac: ENC[AES256_GCM,data:s/Kej+LyNMq8C0KCmI1JEyuuCmcRBLiLIH4EMm8UV7yqklnUCi1A0B7NGvFfhVpJ76kcc+DPRsmvTJIS6yD2/jW82qcsW9gHxDiBHKBQdktzyyR/0Rs912+V/cejF8ZmU0M+0BHvphjrRLBM2M0Qh1ewDh4+RoULdfbADdwnAuM=,iv:mIHC+Y+PFXSNxZIBoYzgVMDAxtndNhIjbGXMUJBD/a0=,tag:FMvJV19mSp6KVoxVJ2/p0A==,type:str]
    version: 3.13.1
