apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - hermes-agent-secrets.sops.yaml
  - configmap.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - pvc.yaml
  - service.yaml
  - ingress.yaml
  - signal-cli-deployment.yaml
  - signal-cli-pvc.yaml
  - signal-cli-service.yaml
